services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: takamol_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      PHP_OPCACHE_ENABLE: "1"
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
    networks:
      - takamol

  webserver:
    image: nginx:1.25-alpine
    container_name: takamol_webserver
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - takamol

  db:
    image: mariadb:latest
    container_name: takamol_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: takamol
      MYSQL_USER: takamol
      MYSQL_PASSWORD: takamol
    networks:
      - takamol

networks:
  takamol:
